import assert from 'node:assert/strict';
const storage=initial=>{const map=new Map(Object.entries(initial));return {getItem:key=>map.get(key)||null,setItem:(key,value)=>map.set(key,value),removeItem:key=>map.delete(key)};};
globalThis.sessionStorage=storage({'tao-journey-token':'expired-token'});
globalThis.localStorage=storage({'tao-token':'older-prototype-token'});
const calls=[];let resolveExpired;
globalThis.fetch=async(path,options)=>{
  calls.push({path,options});
  if(path==='/personas')return new Promise(resolve=>{resolveExpired=resolve;});
  return {ok:true,status:200,json:async()=>({authToken:'new-valid-token'})};
};
const {api}=await import('../app/public/journey/api.js');
const oldRequest=api.request('/personas').catch(error=>error);
await api.authenticate('login','  Existing_User  ',' unchanged password ');
assert.deepEqual(JSON.parse(calls[1].options.body),{authUsername:'Existing_User',authPassword:' unchanged password '});
assert.equal(calls[1].options.headers.Authorization,undefined,'login must not send an expired bearer');
resolveExpired({ok:false,status:401,json:async()=>({error:'Invalid username, password, or session'})});
const oldError=await oldRequest;
assert.equal(oldError.staleSession,true);assert.equal(api.authenticated,true);
assert.equal(sessionStorage.getItem('tao-journey-token'),'new-valid-token');
assert.equal(localStorage.getItem('tao-token'),null);
globalThis.fetch=async()=>({ok:false,status:401,json:async()=>({error:'legacy generic error'})});
await assert.rejects(api.authenticate('login','Existing_User','wrong'),/User ID or password is incorrect/);
assert.equal(api.authenticated,true,'failed credentials cannot revoke a separate valid session');
await assert.rejects(api.request('/personas'),/session is no longer valid/);
assert.equal(api.authenticated,false);
assert.equal(sessionStorage.getItem('tao-journey-token'),null);
globalThis.fetch=async()=>({ok:false,status:409,json:async()=>({error:'That username is already registered'})});
await assert.rejects(api.authenticate('register','Existing_User','password'),error=>error.status===409&&/already registered/.test(error.message));
console.log('ok - expired session race, distinct credential errors, session cleanup, duplicate registration');
