import assert from 'node:assert/strict';
import {splashMarkup,bindSplashTerms} from '../app/public/journey/splash.js';
const markup=splashMarkup();
const positions=['Tao of Lila</h1>','A contemplative meeting','class="splash-artwork"','href="#login"','href="#signup"','Every question opens a path.'].map(text=>markup.indexOf(text));
assert.ok(positions.every((n,i)=>n>=0&&(i===0||n>positions[i-1])),'requested visual hierarchy');
assert.match(markup,/src="\/assets\/splash\/a_richly_detailed_ornate_fantasy_chinese_taoist_i.png"/);
assert.match(markup,/aria-describedby="lila-explanation"/);
assert.match(markup,/aria-describedby="iching-explanation"/);
assert.match(markup,/An ancient Indian game of self-knowledge/);
assert.match(markup,/The ancient Chinese Book of Changes/);
class Node extends EventTarget{attrs={};setAttribute(k,v){this.attrs[k]=v;}}
const makeTerm=()=>{const term=new Node(),button=new Node(),tooltip=new Node();tooltip.hidden=true;term.querySelector=s=>s==='button'?button:tooltip;term.contains=node=>[term,button,tooltip].includes(node);return {term,button,tooltip};};
const first=makeTerm(),second=makeTerm(),root=new Node(),artwork=new Node();
root.querySelectorAll=()=>[first.term,second.term];root.querySelector=()=>artwork;artwork.hidden=true;artwork.complete=false;
const fire=(node,type,props={})=>{const event=new Event(type);for(const [k,v] of Object.entries(props))Object.defineProperty(event,k,{value:v});node.dispatchEvent(event);};
const dispose=bindSplashTerms(root);
fire(first.term,'pointerenter',{pointerType:'mouse'});assert.equal(first.tooltip.hidden,false);assert.equal(first.button.attrs['aria-expanded'],'true');
fire(first.term,'pointerleave',{pointerType:'mouse'});assert.equal(first.tooltip.hidden,true);
fire(first.term,'focusin');assert.equal(first.tooltip.hidden,false);
fire(first.term,'focusout',{relatedTarget:null});assert.equal(first.tooltip.hidden,true);
fire(first.term,'pointerenter',{pointerType:'touch'});assert.equal(first.tooltip.hidden,true);
fire(first.term,'focusin');fire(first.button,'click');assert.equal(first.tooltip.hidden,false,'touch focus followed by click keeps explanation open');
fire(second.button,'click');assert.equal(first.tooltip.hidden,true);assert.equal(second.tooltip.hidden,false);
fire(root,'pointerdown',{target:second.tooltip});assert.equal(second.tooltip.hidden,false);
fire(root,'pointerdown');assert.equal(second.tooltip.hidden,true,'outside tap dismisses');
fire(first.button,'click');fire(root,'keydown',{key:'Escape'});assert.equal(first.tooltip.hidden,true);
fire(artwork,'load');assert.equal(artwork.hidden,false);
dispose();fire(first.button,'click');assert.equal(first.tooltip.hidden,true,'route disposal removes handlers');
console.log('ok - splash hierarchy, asset reference, distinct explanations, hover, focus, touch, outside dismissal, Escape and cleanup');
